networks:
  minetest_network:
    driver: bridge

services:
  luanti:
    image: ghcr.io/luanti-org/luanti:5.15.2
    container_name: tiny_shelter
    command: >
      ./bin/minetestserver --config /home/minetest/.minetest/minetest.conf --world /home/minetest/.minetest/worlds/tiny_shelter
    ports:
      - "30003:30003/udp"
      - "30003:30003/tcp"
    volumes:
      - ./luanti_files:/home/minetest/.minetest/
    environment:
      - HOME=/home/minetest
    restart: always
    networks:
      - minetest_network
    depends_on:
      - discord_relay

  translator:
    image: libretranslate/libretranslate
    container_name: libretranslate
    ports:
      - "5000:5000"
    restart: always
    networks:
      - minetest_network

  discord_relay:
    image: python:3.11-slim
    container_name: discord_relay
    working_dir: /app
    command: >
      sh -c "pip install aiohttp discord.py && python server.py"
    ports:
      - "8080:8080"
    volumes:
      - ./luanti_files/games/minetest_game/mods/discordmt:/app
    restart: always
    networks:
      - minetest_network
