local api = mobs_balrog.api
local settings = mobs_balrog.settings

mobs:register_mob("mobs_balrog:balrog", {
	nametag = "",
	type = "monster",
	hp_min = 1000,
	hp_max = 3000,
	armor = {
		fleshy = 50,
		fire = 0,
	},
	lifetimer = settings.lifetimer,
	walk_velocity = 3.5,
	run_velocity = 5.2,
	walk_chance = settings.walk_chance,
	jump_height = 0,
	stepheight = 2.2,
	replace_rate = 1,
	replace_what = {
		{ "air", settings.flame_node, -2 },
	},
	view_range = settings.view_range,
	knock_back = false,
	immune_to = {
		{ "mobs_balrog:balrog_whip" },
	},
	fear_height = 0,
	fall_damage = 0,
	water_damage = 7,
	lava_damage = 0,
	fire_damage = 0,
	light_damage = 0,
	damage = 20,
	suffocation = 0,
	floats = 0,
	reach = 5,
	attack_animals = false,
	attack_monsters = false,
	group_attack = false,
	attack_type = "dogfight",
	blood_amount = 0,
	pathfinding = settings.pathfinding,
	makes_footstep_sound = true,
	sounds = {
		distance = settings.view_range * 8,
		random = "mobs_balrog_random",
		war_cry = "mobs_balrog_war_cry",
		death = "mobs_balrog_death",
		attack = "mobs_balrog_attack",
	},
	drops = {
      {name = "mobs_balrog:balrog_whip",
		chance = 200,
		min = 0,
		max = 1},
      {name = "default:diamond",
		chance = 2,
		min = 0,
		max = 5},
      {name = "default:mese_crystal",
		chance = 2,
		min = 0,
		max = 5},
      {name = "default:sword_diamond",
		chance = 2,
		min = 0,
		max = 2},
      {name = "x_obsidianmese:sword",
		chance = 4,
		min = 0,
		max = 3},
      {name = "x_obsidianmese:sword_engraved",
		chance = 4,
		min = 0,
		max = 2},
      {name = "x_obsidianmese:pick",
		chance = 2,
		min = 1,
		max = 2},
      {name = "default:mese",
		chance = 1,
		min = 0,
		max = 6},
      {name = "default:diamondblock",
		chance = 1,
		min = 0,
		max = 6},
      {name = "x_obsidianmese:pick_engraved",
		chance = 2,
		min = 0,
		max = 2},
      {name = "3d_armor:boots_diamond",
		chance = 1,
		min = 0,
		max = 2},
      {name = "3d_armor:boots_nether",
		chance = 10,
		min = 0,
		max = 2},
      {name = "3d_armor:chestplate_diamond",
		chance = 1,
		min = 0,
		max = 2},
      {name = "3d_armor:chestplate_nether",
		chance = 10,
		min = 1,
		max = 2},
      {name = "3d_armor:leggings_diamond",
		chance = 1,
		min = 1,
		max = 2},
      {name = "3d_armor:leggings_nether",
		chance = 10,
		min = 1,
		max = 2},
      {name = "3d_armor:helmet_diamond",
		chance = 1,
		min = 0,
		max = 2},
      {name = "3d_armor:helmet_nether",
		chance = 10,
		min = 1,
		max = 2},
      {name = "shields:shield_diamond",
		chance = 1,
		min = 0,
		max = 2},
      {name = "shields:shield_nether",
		chance = 10,
		min = 1,
		max = 2},
      {name = "x_obsidianmese:mese_apple",
		chance = 1,
		min = 0,
		max = 10},
      {name = "farming:burger",
		chance = 1,
		min = 0,
		max = 99},
      {name = "moreores:mithril_lump",
		chance = 1,
		min = 0,
		max = 99},
      {name = "tnt:tnt",
		chance = 5,
		min = 0,
		max = 1},
      {name = "ethereal:glostone",
		chance = 1,
		min = 0,
		max = 99},
      {name = "mob_horse:horse",
		chance = 1,
		min = 0,
		max = 1},
      {name = "ethereal:crystal_block",
		chance = 10,
		min = 0,
		max = 2},
      {name = "mobs:lava_orb",
		chance = 2,
		min = 0,
		max = 1},
      {name = "xdecor:turbo_trampoline",
		chance = 2,
		min = 1,
		max = 1},
      {name = "memeblocks:WW3",
		chance = 10,
		min = 1,
		max = 1},
      {name = "memeblocks:banana",
		chance = 10,
		min = 1,
		max = 1},
      {name = "memeblocks:bird",
		chance = 10,
		min = 1,
		max = 1},
      {name = "memeblocks:cat",
		chance = 10,
		min = 1,
		max = 1},
      {name = "memeblocks:drphill",
		chance = 10,
		min = 1,
		max = 1},
      {name = "memeblocks:frog",
		chance = 10,
		min = 1,
		max = 1},
      {name = "memeblocks:jerry",
		chance = 10,
		min = 1,
		max = 1},
      {name = "memeblocks:kermet",
		chance = 10,
		min = 1,
		max = 1},
      {name = "memeblocks:kolobanga",
		chance = 10,
		min = 1,
		max = 1},
      {name = "memeblocks:patrik",
		chance = 10,
		min = 1,
		max = 1},
      {name = "memeblocks:shrek",
		chance = 10,
		min = 1,
		max = 1},
      {name = "memeblocks:stonks",
		chance = 10,
		min = 1,
		max = 1},
      {name = "memeblocks:thomas",
		chance = 10,
		min = 1,
		max = 1},
      {name = "memeblocks:yobama",
		chance = 10,
		min = 1,
		max = 1},
      {name = "memeblocks:yolo",
		chance = 10,
		min = 1,
		max = 1},
      {name = "ebitems:miraclehealing",
		chance = 10,
		min = 1,
		max = 10},
      {name = "ethereal:lemonade",
		chance = 20,
		min = 1,
		max = 10},
      {name = "farming:spaghetti",
		chance = 10,
		min = 1,
		max = 10},
      {name = "kartcar:kart",
		chance = 10,
		min = 1,
		max = 1},
      {name = "mobs_animal:kitten",
		chance = 10,
		min = 1,
		max = 1},
      {name = "petards:bengal",
		chance = 10,
		min = 1,
		max = 1},
      {name = "technic:gold_chest",
		chance = 10,
		min = 1,
		max = 1},
      {name = "x_obsidianmese:chest",
		chance = 10,
		min = 1,
		max = 1},
      {name = "xdecor:enderchest",
		chance = 10,
		min = 1,
		max = 1},
      {name = "unified_inventory:bag_large",
		chance = 10,
		min = 1,
		max = 1},
      {name = "sandwiches:club_sandwich",
		chance = 10,
		min = 1,
		max = 10},
      {name = "spawners_env:mobs_animal_chicken_spawner",
		chance = 100,
		min = 1,
		max = 1},
      {name = "heated:heated",
		chance = 100,
		min = 1,
		max = 1},
      {name = "cannon73:shell",
		chance = 5,
		min = 0,
		max = 1}							
	},
	visual = "mesh",
	visual_size = { x = 4, y = 4 },
	collisionbox = { -0.8, -4.0, -0.8, 0.8, 4.5, 0.8 },
	textures = { "mobs_balrog_balrog.png" },
	mesh = "mobs_balrog.b3d",
	rotate = 180,
	animation = {
		stand_start = 0,
		stand_end = 240,
		walk_start = 240,
		walk_end = 300,
		walk_speed = 30,
		run_speed = 45,
		punch_start = 300,
		punch_end = 380,
		punch_speed = 45,
	},
	custom_attack = function(...)
		return api.custom_attack(...)
	end,
	
	--
	on_die = function(self, pos)
    self.object:remove()

    minetest.after(0.1, function()
        -- This has been taken from ../tnt/init.lua @243
        minetest.add_particlespawner({
            amount = 128,
            time = 0.1,
            minpos = vector.subtract(pos, 10 / 2),
            maxpos = vector.add(pos, 10 / 2),
            minvel = {x = -3, y = 0, z = -3},
            maxvel = {x = 3, y = 5,  z = 3},
            minacc = {x = 0, y = -10, z = 0},
            maxacc = {x = 0, y = -10, z = 0},
            minexptime = 0.8,
            maxexptime = 2.0,
            minsize = 10 * 0.66,
            maxsize = 10 * 2,
            texture = "fire_basic_flame.png",
            collisiondetection = true,
        })
    end)
	
    balrog_not_died = false	
    minetest.chat_send_all(minetest.colorize("red", "BALROG: You won the battle, but I will be back!"))
    minetest.chat_send_all(minetest.colorize("yellow", "** Balrog will spawn after 1 hour! **"))
    minetest.after(half_hour_after_kill, function()
    	minetest.chat_send_all(minetest.colorize("yellow", "** Balrog will spawn after 30 minutes! **"))
    		minetest.after(twenty_minutes_after_half_hour, function()
    			minetest.chat_send_all(minetest.colorize("yellow", "** Balrog will spawn after 10 minutes! **"))
    			minetest.after(five_minutes, function()
    				minetest.chat_send_all(minetest.colorize("yellow", "** Balrog will spawn after 5 minutes! **"))
    				minetest.after(five_minutes, function()
					balrog_not_died = true	
					minetest.chat_send_all(minetest.colorize("yellow", "** Balrog has spawned at the world! **"))
					minetest.chat_send_all(minetest.colorize("red", "BALROG: HA HA HA I'm back! Anyone who dares to come to me will be defeated!"))
				end)	
			end)	
		end)
    end)

--
	end,
	do_custom = function(...)
		return api.do_custom(...)
	end,
	on_blast = function(...)
		return api.on_blast(...)
	end,
	after_activate = function(self, staticdata, def, dtime)
		api.heal(self, dtime)
	end,
})

mobs:register_egg(
	"mobs_balrog:balrog",
	"Balrog",
	"mobs_balrog_flame.png", -- the texture displayed for the egg in inventory
	1, -- egg image in front of your texture (1 = yes, 0 = no)
	false -- if set to true this stops spawn egg appearing in creative
)
